/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) STM_model_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {3, 3, 1};
static const casadi_int casadi_s2[3] = {3, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* STM_model_expl_vde_forw:(i0[3],i1[3x3],i2[3x2],i3[2],i4[0])->(o0[3],o1[3x3],o2[3x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  a00=arg[3]? arg[3][0] : 0;
  a01=4.6107000000000006e+01;
  a02=arg[3]? arg[3][1] : 0;
  a03=arg[0]? arg[0][1] : 0;
  a04=2.8000000000000003e-01;
  a05=arg[0]? arg[0][2] : 0;
  a06=(a04*a05);
  a07=(a03+a06);
  a08=arg[0]? arg[0][0] : 0;
  a09=atan2(a07,a08);
  a09=(a02-a09);
  a10=1.2385714333513004e-01;
  a09=(a09/a10);
  a09=tanh(a09);
  a10=(a01*a09);
  a11=sin(a02);
  a12=(a10*a11);
  a13=(a00-a12);
  a14=1.8800000000000001e+01;
  a13=(a13/a14);
  a15=(a05*a03);
  a13=(a13+a15);
  if (res[0]!=0) res[0][0]=a13;
  a02=cos(a02);
  a13=(a10*a02);
  a15=0.;
  a16=1.8784058747364004e+03;
  a17=casadi_sq(a00);
  a16=(a16-a17);
  a17=casadi_fmax(a15,a16);
  a17=sqrt(a17);
  a06=(a03-a06);
  a18=atan2(a06,a08);
  a19=1.1340500000000000e+03;
  a19=(a17/a19);
  a20=9.9999999999999995e-07;
  a19=(a19+a20);
  a21=atan(a19);
  a21=(a21+a20);
  a18=(a18/a21);
  a20=(-a18);
  a20=tanh(a20);
  a22=(a17*a20);
  a23=(a13+a22);
  a23=(a23/a14);
  a14=(a05*a08);
  a23=(a23-a14);
  if (res[0]!=0) res[0][1]=a23;
  a10=(a04*a10);
  a23=(a10*a02);
  a22=(a04*a22);
  a23=(a23-a22);
  a22=1.4739200000000003e+00;
  a23=(a23/a22);
  if (res[0]!=0) res[0][2]=a23;
  a23=5.3191489361702128e-02;
  a22=1.;
  a09=casadi_sq(a09);
  a09=(a22-a09);
  a14=8.0738177312407498e+00;
  a24=casadi_sq(a07);
  a25=casadi_sq(a08);
  a24=(a24+a25);
  a26=(a08/a24);
  a27=arg[1]? arg[1][1] : 0;
  a28=arg[1]? arg[1][2] : 0;
  a29=(a04*a28);
  a30=(a27+a29);
  a30=(a26*a30);
  a07=(a07/a24);
  a24=arg[1]? arg[1][0] : 0;
  a31=(a07*a24);
  a30=(a30-a31);
  a30=(a14*a30);
  a30=(a09*a30);
  a30=(a01*a30);
  a31=(a11*a30);
  a31=(a23*a31);
  a32=(a03*a28);
  a33=(a05*a27);
  a32=(a32+a33);
  a31=(a31+a32);
  if (res[1]!=0) res[1][0]=a31;
  a31=(a02*a30);
  a32=casadi_sq(a20);
  a32=(a22-a32);
  a33=casadi_sq(a06);
  a33=(a33+a25);
  a25=(a08/a33);
  a27=(a27-a29);
  a27=(a25*a27);
  a06=(a06/a33);
  a33=(a06*a24);
  a27=(a27-a33);
  a27=(a27/a21);
  a27=(a32*a27);
  a27=(a17*a27);
  a31=(a31+a27);
  a31=(a23*a31);
  a28=(a08*a28);
  a24=(a05*a24);
  a28=(a28+a24);
  a31=(a31+a28);
  a31=(-a31);
  if (res[1]!=0) res[1][1]=a31;
  a31=6.7846287451150655e-01;
  a27=(a04*a27);
  a30=(a04*a30);
  a30=(a02*a30);
  a27=(a27-a30);
  a27=(a31*a27);
  if (res[1]!=0) res[1][2]=a27;
  a27=arg[1]? arg[1][4] : 0;
  a30=arg[1]? arg[1][5] : 0;
  a28=(a04*a30);
  a24=(a27+a28);
  a24=(a26*a24);
  a33=arg[1]? arg[1][3] : 0;
  a29=(a07*a33);
  a24=(a24-a29);
  a24=(a14*a24);
  a24=(a09*a24);
  a24=(a01*a24);
  a29=(a11*a24);
  a29=(a23*a29);
  a34=(a03*a30);
  a35=(a05*a27);
  a34=(a34+a35);
  a29=(a29+a34);
  if (res[1]!=0) res[1][3]=a29;
  a29=(a02*a24);
  a27=(a27-a28);
  a27=(a25*a27);
  a28=(a06*a33);
  a27=(a27-a28);
  a27=(a27/a21);
  a27=(a32*a27);
  a27=(a17*a27);
  a29=(a29+a27);
  a29=(a23*a29);
  a30=(a08*a30);
  a33=(a05*a33);
  a30=(a30+a33);
  a29=(a29+a30);
  a29=(-a29);
  if (res[1]!=0) res[1][4]=a29;
  a27=(a04*a27);
  a24=(a04*a24);
  a24=(a02*a24);
  a27=(a27-a24);
  a27=(a31*a27);
  if (res[1]!=0) res[1][5]=a27;
  a27=arg[1]? arg[1][7] : 0;
  a24=arg[1]? arg[1][8] : 0;
  a29=(a04*a24);
  a30=(a27+a29);
  a30=(a26*a30);
  a33=arg[1]? arg[1][6] : 0;
  a28=(a07*a33);
  a30=(a30-a28);
  a30=(a14*a30);
  a30=(a09*a30);
  a30=(a01*a30);
  a28=(a11*a30);
  a28=(a23*a28);
  a34=(a03*a24);
  a35=(a05*a27);
  a34=(a34+a35);
  a28=(a28+a34);
  if (res[1]!=0) res[1][6]=a28;
  a28=(a02*a30);
  a27=(a27-a29);
  a27=(a25*a27);
  a29=(a06*a33);
  a27=(a27-a29);
  a27=(a27/a21);
  a27=(a32*a27);
  a27=(a17*a27);
  a28=(a28+a27);
  a28=(a23*a28);
  a24=(a08*a24);
  a33=(a05*a33);
  a24=(a24+a33);
  a28=(a28+a24);
  a28=(-a28);
  if (res[1]!=0) res[1][7]=a28;
  a27=(a04*a27);
  a30=(a04*a30);
  a30=(a02*a30);
  a27=(a27-a30);
  a27=(a31*a27);
  if (res[1]!=0) res[1][8]=a27;
  a27=arg[2]? arg[2][1] : 0;
  a30=arg[2]? arg[2][2] : 0;
  a28=(a04*a30);
  a24=(a27+a28);
  a24=(a26*a24);
  a33=arg[2]? arg[2][0] : 0;
  a29=(a07*a33);
  a24=(a24-a29);
  a24=(a14*a24);
  a24=(a09*a24);
  a24=(a01*a24);
  a29=(a11*a24);
  a29=(a23*a29);
  a34=(a03*a30);
  a35=(a05*a27);
  a34=(a34+a35);
  a29=(a29+a34);
  a29=(a23+a29);
  if (res[2]!=0) res[2][0]=a29;
  a29=(a15<=a16);
  a16=(a16<=a15);
  a16=(a16+a29);
  a29=(a29/a16);
  a00=(a00+a00);
  a29=(a29*a00);
  a00=(a17+a17);
  a29=(a29/a00);
  a20=(a20*a29);
  a18=(a18/a21);
  a00=8.8179533530267625e-04;
  a00=(a00*a29);
  a19=casadi_sq(a19);
  a22=(a22+a19);
  a00=(a00/a22);
  a18=(a18*a00);
  a18=(a32*a18);
  a18=(a17*a18);
  a20=(a20+a18);
  a18=(a23*a20);
  a00=(a02*a24);
  a27=(a27-a28);
  a27=(a25*a27);
  a28=(a06*a33);
  a27=(a27-a28);
  a27=(a27/a21);
  a27=(a32*a27);
  a27=(a17*a27);
  a00=(a00+a27);
  a00=(a23*a00);
  a30=(a08*a30);
  a33=(a05*a33);
  a30=(a30+a33);
  a00=(a00+a30);
  a18=(a18+a00);
  a18=(-a18);
  if (res[2]!=0) res[2][1]=a18;
  a20=(a04*a20);
  a20=(a31*a20);
  a27=(a04*a27);
  a24=(a04*a24);
  a24=(a02*a24);
  a27=(a27-a24);
  a27=(a31*a27);
  a20=(a20+a27);
  if (res[2]!=0) res[2][2]=a20;
  a20=arg[2]? arg[2][4] : 0;
  a27=arg[2]? arg[2][5] : 0;
  a24=(a04*a27);
  a18=(a20+a24);
  a26=(a26*a18);
  a18=arg[2]? arg[2][3] : 0;
  a07=(a07*a18);
  a26=(a26-a07);
  a26=(a14*a26);
  a26=(a09*a26);
  a26=(a01*a26);
  a07=(a11*a26);
  a07=(a23*a07);
  a03=(a03*a27);
  a00=(a05*a20);
  a03=(a03+a00);
  a07=(a07+a03);
  a14=(a14*a09);
  a01=(a01*a14);
  a14=(a11*a01);
  a14=(a14+a13);
  a14=(a23*a14);
  a07=(a07-a14);
  if (res[2]!=0) res[2][3]=a07;
  a07=(a02*a01);
  a07=(a07-a12);
  a07=(a23*a07);
  a12=(a02*a26);
  a20=(a20-a24);
  a25=(a25*a20);
  a06=(a06*a18);
  a25=(a25-a06);
  a25=(a25/a21);
  a32=(a32*a25);
  a17=(a17*a32);
  a12=(a12+a17);
  a23=(a23*a12);
  a08=(a08*a27);
  a05=(a05*a18);
  a08=(a08+a05);
  a23=(a23+a08);
  a07=(a07-a23);
  if (res[2]!=0) res[2][4]=a07;
  a01=(a04*a01);
  a01=(a02*a01);
  a10=(a10*a11);
  a01=(a01-a10);
  a01=(a31*a01);
  a17=(a04*a17);
  a04=(a04*a26);
  a02=(a02*a04);
  a17=(a17-a02);
  a31=(a31*a17);
  a01=(a01+a31);
  if (res[2]!=0) res[2][5]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int STM_model_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int STM_model_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real STM_model_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* STM_model_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* STM_model_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* STM_model_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* STM_model_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
