/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) STM_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {3, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {5, 1, 1};

/* STM_model_expl_vde_adj:(i0[3],i1[3],i2[2],i3[0])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32;
  a00=arg[0]? arg[0][1] : 0;
  a01=2.8000000000000003e-01;
  a02=arg[0]? arg[0][2] : 0;
  a03=(a01*a02);
  a04=(a00-a03);
  a05=casadi_sq(a04);
  a06=arg[0]? arg[0][0] : 0;
  a07=casadi_sq(a06);
  a05=(a05+a07);
  a08=(a04/a05);
  a09=1.;
  a04=atan2(a04,a06);
  a10=0.;
  a11=1.8784058747364004e+03;
  a12=arg[2]? arg[2][0] : 0;
  a13=casadi_sq(a12);
  a11=(a11-a13);
  a13=casadi_fmax(a10,a11);
  a13=sqrt(a13);
  a14=1.1340500000000000e+03;
  a14=(a13/a14);
  a15=9.9999999999999995e-07;
  a14=(a14+a15);
  a16=atan(a14);
  a16=(a16+a15);
  a04=(a04/a16);
  a15=(-a04);
  a15=tanh(a15);
  a17=casadi_sq(a15);
  a17=(a09-a17);
  a18=5.3191489361702128e-02;
  a19=arg[1]? arg[1][1] : 0;
  a20=(a18*a19);
  a21=6.7846287451150655e-01;
  a22=arg[1]? arg[1][2] : 0;
  a21=(a21*a22);
  a22=(a01*a21);
  a22=(a20-a22);
  a23=(a13*a22);
  a17=(a17*a23);
  a23=(a17/a16);
  a08=(a08*a23);
  a24=(a02*a19);
  a08=(a08-a24);
  a03=(a00+a03);
  a24=casadi_sq(a03);
  a24=(a24+a07);
  a07=(a03/a24);
  a25=8.0738177312407498e+00;
  a26=arg[2]? arg[2][1] : 0;
  a03=atan2(a03,a06);
  a03=(a26-a03);
  a27=1.2385714333513004e-01;
  a03=(a03/a27);
  a03=tanh(a03);
  a27=casadi_sq(a03);
  a27=(a09-a27);
  a28=4.6107000000000006e+01;
  a29=cos(a26);
  a30=(a29*a21);
  a30=(a01*a30);
  a31=(a29*a20);
  a30=(a30+a31);
  a26=sin(a26);
  a31=arg[1]? arg[1][0] : 0;
  a18=(a18*a31);
  a32=(a26*a18);
  a30=(a30-a32);
  a30=(a28*a30);
  a27=(a27*a30);
  a25=(a25*a27);
  a07=(a07*a25);
  a08=(a08+a07);
  if (res[0]!=0) res[0][0]=a08;
  a02=(a02*a31);
  a05=(a06/a05);
  a05=(a05*a23);
  a02=(a02-a05);
  a24=(a06/a24);
  a24=(a24*a25);
  a02=(a02-a24);
  if (res[0]!=0) res[0][1]=a02;
  a05=(a01*a05);
  a06=(a06*a19);
  a05=(a05-a06);
  a00=(a00*a31);
  a05=(a05+a00);
  a24=(a01*a24);
  a05=(a05-a24);
  if (res[0]!=0) res[0][2]=a05;
  a12=(a12+a12);
  a05=(a10<=a11);
  a11=(a11<=a10);
  a11=(a11+a05);
  a05=(a05/a11);
  a15=(a15*a22);
  a22=8.8179533530267625e-04;
  a04=(a04/a16);
  a04=(a04*a17);
  a14=casadi_sq(a14);
  a09=(a09+a14);
  a04=(a04/a09);
  a22=(a22*a04);
  a15=(a15+a22);
  a13=(a13+a13);
  a15=(a15/a13);
  a05=(a05*a15);
  a12=(a12*a05);
  a12=(a18-a12);
  if (res[0]!=0) res[0][3]=a12;
  a28=(a28*a03);
  a01=(a01*a28);
  a01=(a01*a21);
  a01=(a26*a01);
  a20=(a28*a20);
  a26=(a26*a20);
  a01=(a01+a26);
  a28=(a28*a18);
  a29=(a29*a28);
  a01=(a01+a29);
  a25=(a25-a01);
  if (res[0]!=0) res[0][4]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void STM_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int STM_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int STM_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real STM_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* STM_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* STM_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* STM_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* STM_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int STM_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
